Fg/fix o auth token refresh
openedx/tutor-contrib-aspects pull request #203
Opened 2023-07-26 16:49 UTC by nandodev-net

## fix: OAuth token refresh error #152

This pull request implements the functionality of refreshing OAuth tokens when they have expired, enhancing the OAuth2 authentication process.

#### Changes include:

_refresh_token_ function: This function is designed to refresh the OAuth tokens when they have expired. It sends a POST request to the LMS's oauth2/access_token/ endpoint with the necessary data to refresh the token. If the request is successful (HTTP 200), it returns a new token; otherwise, it returns the original token.

_is_token_expired_ function: This is a helper function that checks whether the OAuth token is expired. It compares the token's expiration time with the current time to determine the token's status.

_get_oauth_token_ function: Updated this function to make use of is_token_expired and refresh_token. When an OAuth token is retrieved, it checks whether the token is expired. If it is, the token is refreshed.

#### To verify the functionality of this PR:

1. Allow a token to expire.
2. Initiate a request that requires OAuth authentication.
3. Verify that the is_token_expired function correctly identifies the expired token.
4. Verify that the refresh_token function is triggered and that it returns a new token when the original token is expired.
5. Confirm that get_oauth_token successfully retrieves a refreshed token when the original is expired.

Please review and provide feedback.

Feel free to further modify as needed.

2023-07-26 16:51 UTC, Ian2012 commented on tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
> +                    logging.error("Failed to refresh the token: {}".format(e))
Does this log something PII?

2023-07-26 16:51 UTC, Ian2012 commented on tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
> +                    new_token = {}
It would be better to throw the error and remove the log

2023-07-26 16:52 UTC, Ian2012 commented on tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
> +        # The token is expired if the current time is greater than the expiry time
Remove too verbose comment

2023-07-26 16:54 UTC, Ian2012 commented on tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
> +            # Sets up the data to be sent with the POST request.
Remove too verbose comment

2023-07-26 19:43 UTC, Ian2012 requested changes

2023-07-27 15:21 UTC, Ian2012 commented
@bmtcril any comments here?

2023-07-27 16:09 UTC, Ian2012 approved these changes

2023-07-27 16:34 UTC, bmtcril approved these changes
Thanks for the contribution, LGTM! @Ian2012  do you want to merge it when you're ready?

2023-07-27 16:54 UTC, merged