feat: Add student role with minimal access in Superset
openedx/tutor-contrib-aspects pull request #307
Opened 2023-08-17 23:24 UTC by nandodev-net

### Description:
This pull request introduces a new role for students, designed to be similar to the instructor role but with read-only access. The aim is to ensure students can only access and view assets for which they have permissions.

### Changes:

- Defined a base student role with minimal permissions.
- Automated role assignment for students upon login.

### Testing:

- Logged in as a student and verified only read access to permitted assets.
- Checked automatic role assignment mechanism.

Please review the changes and provide feedback.

2023-08-17 23:24 UTC, openedx-webhooks commented
Thanks for the pull request, @nandodev-net!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

<!-- comment:end_of_wip -->




<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IHRydWV9 -->

2023-08-18 03:41 UTC, Ian2012 commented
You are missing the part where the role should be assigned automatically at login.

https://github.com/openedx/tutor-contrib-aspects/blob/8a5c23633f015d0e65f9aafed358658e16843882/tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py#L177-L178

You can use something similar to this:
```python
if roles:
    return roles
if not bool("{{SUPERSET_BLOCK_STUDENT_ACCESS}}"):
   return ["student", f"student - {language}"]
raise Exception(f"Student {username} tried to access Superset")
```

2023-08-18 03:42 UTC, Ian2012 commented
Also, as you are replicating the permissions for the instructor role. Can you create a template that holds the shared permissions for both roles and inject it where it corresponds?

2023-08-21 14:43 UTC, Ian2012 commented
cc @nandodev-net

2023-08-22 12:49 UTC, Ian2012 requested changes

2023-08-22 12:49 UTC, Ian2012 commented on tutoraspects/templates/aspects/apps/superset/pythonpath/superset_config_docker.py
> +    AUTH_ROLES_MAPPING[f"student-{language}"] = [f"{{SUPERSET_ROLES_MAPPING.student}} - {language}"]
@nandodev-net can you include the operator here too? Seems like it's missing

2023-08-22 20:45 UTC, Ian2012 commented on config.yml
Please remove this file

2023-08-24 19:24 UTC, Ian2012 approved these changes

2023-08-24 19:46 UTC, bmtcril commented on tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
> +                    return ["student", f"student - {language}"]
Other language roles don't have spaces around the dash

2023-08-24 19:46 UTC, bmtcril commented on tutoraspects/templates/aspects/apps/superset/pythonpath/openedx_sso_security_manager.py
> +                    return roles
I'm somewhat concerned about this logic. Having a `student` role returned here would override `SUPERSET_BLOCK_STUDENT_ACCESS`. Maybe not a big deal, but can we add a check for that and throw an exception if it happens?

2023-08-25 12:10 UTC, bmtcril approved these changes
Thanks @nandodev-net , looks good to me!

2023-08-25 12:42 UTC, merged

2023-08-25 12:42 UTC, openedx-webhooks commented
@nandodev-net 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/tutor-contrib-aspects&entry.867055334=https://github.com/openedx/tutor-contrib-aspects/pull/307&entry.1484655318=https://github.com/nandodev-net&entry.752974735=2023-08-17+23:24&entry.1917517419=2023-08-25+12:42&entry.2133058324=Yes) so we can improve your experience in the future.

<!-- comment:end_survey -->