chore: Upgrade xapi-db-load to 1.0
openedx/tutor-contrib-aspects pull request #550
Opened 2023-12-20 19:42 UTC by bmtcril

2023-12-20 20:41 UTC, bmtcril commented
Hmm, tests all passed but there are actually errors in the logs. >_>

```
clickhouse_connect.driver.exceptions.DatabaseError: :HTTPDriver for http://clickhouse:8123 returned response code 404)
 Code: 60. DB::Exception: Table xapi.xapi_events_all_parsed does not exist. Maybe you meant xapi_events_all?. 
```

2023-12-20 20:46 UTC, bmtcril commented
Oh, ha, dbt is creating everything in the reporting schema. That complicates things. cc @SoryRawyer 

`2 of 19 START sql materialized_view model `reporting`.`xapi_events_all_parsed` . [RUN]`

2023-12-20 20:59 UTC, Ian2012 requested changes

2023-12-20 20:59 UTC, Ian2012 commented on tutoraspects/templates/aspects/apps/aspects/scripts/xapi-db-load-config.yaml
@bmtcril can you add a patch here so that we can customize this file as needed?

2023-12-20 20:59 UTC, Ian2012 commented on tutoraspects/commands_v0.py
> +    bash clickhouse-demo-xapi-data.sh {config_file}
The config_file parameter can't be used in docker/k8s unless we mounted it somehow in the aspects Pod. I think you should remove it and leave a patch or a setting that allows to modify the `xapi-db-load-config.yaml` and use that file by default

2024-01-16 19:56 UTC, bmtcril commented
@Ian2012 this should be ready for re-review

2024-01-18 17:05 UTC, Ian2012 approved these changes

2024-01-18 17:05 UTC, merged