chore: Update automation for new default branch
openedx/tutor-contrib-aspects pull request #809
Opened 2024-05-13 19:12 UTC by bmtcril

We moved from "main" to "nightly" to better match Tutor standard release branch naming conventions.

2024-05-13 20:42 UTC, bmtcril commented
Hmm actions aren't running, going to close and reopen

2024-05-13 21:00 UTC, kdmccormick approved these changes

2024-05-14 13:30 UTC, Ian2012 approved these changes

2024-05-14 13:31 UTC, Ian2012 requested changes

2024-05-14 13:50 UTC, bmtcril commented on catalog-info.yaml
> +    openedx.org/release: "nightly"
It's already tagged for redwood, and we still have some things to talk about around this so I'd like to get this merged and remove the tag later if we need to.

2024-05-14 13:50 UTC, kdmccormick commented on catalog-info.yaml
> +    openedx.org/release: "nightly"
+1

2024-05-14 13:56 UTC, Ian2012 approved these changes

2024-05-14 13:56 UTC, merged